FROM openjdk:11

ARG GAME_SERVICE_VERSION
ENV GAME_SERVICE_VERSION ${GATEWAY_VERSION:-0.0.1}

ARG HOSTNAME
ENV HOSTNAME ${HOSTNAME:-"0.0.0.0"}

ARG SCALA_VERSION
ENV SCALA_VERSION ${SCALA_VERSION:-2.13}

ARG PORT
ENV PORT ${PORT:-9081}

#DB ENV VAR
ARG DB_HOST
ENV DB_HOST ${DB_HOST:-"localhost"}
ARG DB_PORT
ENV DB_PORT ${DB_PORT:-"5432"}
ARG DB_NAME
ENV DB_NAME ${DB_NAME:-"postgres"}
ARG DB_USER
ENV DB_USER ${DB_USER:-"postgres"}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD:-"123"}

COPY target/scala-2.13/GameService-assembly-${GAME_SERVICE_VERSION}.jar /service/gateway.jar

EXPOSE ${PORT}
WORKDIR /service

CMD ["java", "-jar", "gateway.jar"]

